#!/bin/bash

# ✅ PRE-CHECKS
echo "🔍 Checking project environment..."

REQUIRED_PKGS=("crewai" "a_mem" "python-dotenv")
for pkg in "${REQUIRED_PKGS[@]}"; do
  pip show "$pkg" &>/dev/null || pip install "$pkg"
done

mkdir -p mystic-agents
mkdir -p agent_logs

# ✅ CREATE TEMPLATED FILES IF NOT PRESENT
touch_if_missing() {
  FILE=$1
  TEMPLATE=$2
  if [ ! -f "$FILE" ]; then
    echo "🔧 Creating $FILE..."
    echo -e "$TEMPLATE" > "$FILE"
  else
    echo "✅ $FILE already exists, skipping."
  fi
}

touch_if_missing "claude.md" "# claude.md\n\n## Onboarding State: Incomplete"
touch_if_missing "gemini.md" "# gemini.md\n\n## Gemini Session Log"
touch_if_missing "FRD.md" "# Feature Requirements Document"
touch_if_missing "FRS.md" "# Functional Requirements Spec"
touch_if_missing ".env.local" "# AUTOGENERATED - Update with your secrets\n"
touch_if_missing "README.md" "# Project Setup\n\n## Features:\n- Agents\n- Memory\n- MCP\n"

echo "✅ All context files ready."